-- MySQL Script generated by MySQL Workbench
-- Sat Nov 14 12:39:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehicle` (
  `device_id` INT NOT NULL,
  `timestep` INT NOT NULL,
  `real_lat` DOUBLE NOT NULL,
  `real_long` DOUBLE NOT NULL,
  `predicted_lat` DOUBLE NOT NULL,
  `predicted_long` DOUBLE NOT NULL,
  `real_rsssi` FLOAT NOT NULL,
  `real_throughput` FLOAT NOT NULL,
  `predicted_rssi` FLOAT NOT NULL,
  `predicted_throughput` FLOAT NOT NULL,
  `speed` DOUBLE NULL,
  `angle` DOUBLE NULL,
  PRIMARY KEY (`device_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
